# Generated by Django 5.1.4 on 2025-01-03 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='following',
            field=models.ManyToManyField(related_name='followers_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='followers',
            field=models.ManyToManyField(related_name='following_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
